'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.34003
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="RwData")>  _
Partial Public Class DataRwDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "可扩展性方法定义"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Rw.EntityData.RwEntitySettings.MySettings.Default.RwDataConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property ST_STBPRP_B() As System.Data.Linq.Table(Of ST_STBPRP_B)
		Get
			Return Me.GetTable(Of ST_STBPRP_B)
		End Get
	End Property
	
	Public ReadOnly Property ST_PPTN_R() As System.Data.Linq.Table(Of ST_PPTN_R)
		Get
			Return Me.GetTable(Of ST_PPTN_R)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ST_STBPRP_B")>  _
Partial Public Class ST_STBPRP_B
	
	Private _STCD As String
	
	Private _STNM As String
	
	Private _RVNM As String
	
	Private _HNNM As String
	
	Private _BSNM As String
	
	Private _LGTD_OLD As String
	
	Private _LTTD_OLD As String
	
	Private _STLC As String
	
	Private _ADDVCD As String
	
	Private _MDBZ As System.Nullable(Of Double)
	
	Private _MDPR As System.Nullable(Of Double)
	
	Private _DTMNM As String
	
	Private _DTMEL As System.Nullable(Of Decimal)
	
	Private _STTP As String
	
	Private _DFRTMS As System.Nullable(Of Integer)
	
	Private _FRITM As String
	
	Private _FRGRD As System.Nullable(Of Char)
	
	Private _BGFRYM As String
	
	Private _EDFRYM As String
	
	Private _ADMAUTH As String
	
	Private _STBK As System.Nullable(Of Char)
	
	Private _DRNA As System.Nullable(Of Decimal)
	
	Private _PHCD As String
	
	Private _LGTD As System.Nullable(Of Decimal)
	
	Private _LTTD As System.Nullable(Of Decimal)
	
	Private _DTPR As System.Nullable(Of Decimal)
	
	Private _ESSTYM As String
	
	Private _ATCUNIT As String
	
	Private _LOCALITY As String
	
	Private _STAZT As System.Nullable(Of Decimal)
	
	Private _DSTRVM As System.Nullable(Of Decimal)
	
	Private _USFL As System.Nullable(Of Char)
	
	Private _COMMENTS As String
	
	Private _MODITIME As System.Nullable(Of Date)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STCD", DbType:="Char(8) NOT NULL", CanBeNull:=false)>  _
	Public Property STCD() As String
		Get
			Return Me._STCD
		End Get
		Set
			If (String.Equals(Me._STCD, value) = false) Then
				Me._STCD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STNM", DbType:="Char(30)")>  _
	Public Property STNM() As String
		Get
			Return Me._STNM
		End Get
		Set
			If (String.Equals(Me._STNM, value) = false) Then
				Me._STNM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RVNM", DbType:="Char(30)")>  _
	Public Property RVNM() As String
		Get
			Return Me._RVNM
		End Get
		Set
			If (String.Equals(Me._RVNM, value) = false) Then
				Me._RVNM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HNNM", DbType:="Char(30)")>  _
	Public Property HNNM() As String
		Get
			Return Me._HNNM
		End Get
		Set
			If (String.Equals(Me._HNNM, value) = false) Then
				Me._HNNM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BSNM", DbType:="Char(30)")>  _
	Public Property BSNM() As String
		Get
			Return Me._BSNM
		End Get
		Set
			If (String.Equals(Me._BSNM, value) = false) Then
				Me._BSNM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LGTD_OLD", DbType:="Char(7)")>  _
	Public Property LGTD_OLD() As String
		Get
			Return Me._LGTD_OLD
		End Get
		Set
			If (String.Equals(Me._LGTD_OLD, value) = false) Then
				Me._LGTD_OLD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LTTD_OLD", DbType:="Char(6)")>  _
	Public Property LTTD_OLD() As String
		Get
			Return Me._LTTD_OLD
		End Get
		Set
			If (String.Equals(Me._LTTD_OLD, value) = false) Then
				Me._LTTD_OLD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STLC", DbType:="Char(50)")>  _
	Public Property STLC() As String
		Get
			Return Me._STLC
		End Get
		Set
			If (String.Equals(Me._STLC, value) = false) Then
				Me._STLC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ADDVCD", DbType:="Char(6)")>  _
	Public Property ADDVCD() As String
		Get
			Return Me._ADDVCD
		End Get
		Set
			If (String.Equals(Me._ADDVCD, value) = false) Then
				Me._ADDVCD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MDBZ", DbType:="Float")>  _
	Public Property MDBZ() As System.Nullable(Of Double)
		Get
			Return Me._MDBZ
		End Get
		Set
			If (Me._MDBZ.Equals(value) = false) Then
				Me._MDBZ = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MDPR", DbType:="Float")>  _
	Public Property MDPR() As System.Nullable(Of Double)
		Get
			Return Me._MDPR
		End Get
		Set
			If (Me._MDPR.Equals(value) = false) Then
				Me._MDPR = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DTMNM", DbType:="Char(16)")>  _
	Public Property DTMNM() As String
		Get
			Return Me._DTMNM
		End Get
		Set
			If (String.Equals(Me._DTMNM, value) = false) Then
				Me._DTMNM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DTMEL", DbType:="Decimal(7,3)")>  _
	Public Property DTMEL() As System.Nullable(Of Decimal)
		Get
			Return Me._DTMEL
		End Get
		Set
			If (Me._DTMEL.Equals(value) = false) Then
				Me._DTMEL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STTP", DbType:="Char(2)")>  _
	Public Property STTP() As String
		Get
			Return Me._STTP
		End Get
		Set
			If (String.Equals(Me._STTP, value) = false) Then
				Me._STTP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DFRTMS", DbType:="Int")>  _
	Public Property DFRTMS() As System.Nullable(Of Integer)
		Get
			Return Me._DFRTMS
		End Get
		Set
			If (Me._DFRTMS.Equals(value) = false) Then
				Me._DFRTMS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FRITM", DbType:="Char(32)")>  _
	Public Property FRITM() As String
		Get
			Return Me._FRITM
		End Get
		Set
			If (String.Equals(Me._FRITM, value) = false) Then
				Me._FRITM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FRGRD", DbType:="Char(1)")>  _
	Public Property FRGRD() As System.Nullable(Of Char)
		Get
			Return Me._FRGRD
		End Get
		Set
			If (Me._FRGRD.Equals(value) = false) Then
				Me._FRGRD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BGFRYM", DbType:="Char(6)")>  _
	Public Property BGFRYM() As String
		Get
			Return Me._BGFRYM
		End Get
		Set
			If (String.Equals(Me._BGFRYM, value) = false) Then
				Me._BGFRYM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EDFRYM", DbType:="Char(6)")>  _
	Public Property EDFRYM() As String
		Get
			Return Me._EDFRYM
		End Get
		Set
			If (String.Equals(Me._EDFRYM, value) = false) Then
				Me._EDFRYM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ADMAUTH", DbType:="Char(20)")>  _
	Public Property ADMAUTH() As String
		Get
			Return Me._ADMAUTH
		End Get
		Set
			If (String.Equals(Me._ADMAUTH, value) = false) Then
				Me._ADMAUTH = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STBK", DbType:="Char(1)")>  _
	Public Property STBK() As System.Nullable(Of Char)
		Get
			Return Me._STBK
		End Get
		Set
			If (Me._STBK.Equals(value) = false) Then
				Me._STBK = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DRNA", DbType:="Decimal(7,0)")>  _
	Public Property DRNA() As System.Nullable(Of Decimal)
		Get
			Return Me._DRNA
		End Get
		Set
			If (Me._DRNA.Equals(value) = false) Then
				Me._DRNA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PHCD", DbType:="Char(6)")>  _
	Public Property PHCD() As String
		Get
			Return Me._PHCD
		End Get
		Set
			If (String.Equals(Me._PHCD, value) = false) Then
				Me._PHCD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LGTD", DbType:="Decimal(10,6)")>  _
	Public Property LGTD() As System.Nullable(Of Decimal)
		Get
			Return Me._LGTD
		End Get
		Set
			If (Me._LGTD.Equals(value) = false) Then
				Me._LGTD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LTTD", DbType:="Decimal(10,6)")>  _
	Public Property LTTD() As System.Nullable(Of Decimal)
		Get
			Return Me._LTTD
		End Get
		Set
			If (Me._LTTD.Equals(value) = false) Then
				Me._LTTD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DTPR", DbType:="Decimal(7,3)")>  _
	Public Property DTPR() As System.Nullable(Of Decimal)
		Get
			Return Me._DTPR
		End Get
		Set
			If (Me._DTPR.Equals(value) = false) Then
				Me._DTPR = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESSTYM", DbType:="Char(6)")>  _
	Public Property ESSTYM() As String
		Get
			Return Me._ESSTYM
		End Get
		Set
			If (String.Equals(Me._ESSTYM, value) = false) Then
				Me._ESSTYM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ATCUNIT", DbType:="Char(20)")>  _
	Public Property ATCUNIT() As String
		Get
			Return Me._ATCUNIT
		End Get
		Set
			If (String.Equals(Me._ATCUNIT, value) = false) Then
				Me._ATCUNIT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LOCALITY", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property LOCALITY() As String
		Get
			Return Me._LOCALITY
		End Get
		Set
			If (String.Equals(Me._LOCALITY, value) = false) Then
				Me._LOCALITY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STAZT", DbType:="Decimal(3,0)")>  _
	Public Property STAZT() As System.Nullable(Of Decimal)
		Get
			Return Me._STAZT
		End Get
		Set
			If (Me._STAZT.Equals(value) = false) Then
				Me._STAZT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DSTRVM", DbType:="Decimal(6,1)")>  _
	Public Property DSTRVM() As System.Nullable(Of Decimal)
		Get
			Return Me._DSTRVM
		End Get
		Set
			If (Me._DSTRVM.Equals(value) = false) Then
				Me._DSTRVM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USFL", DbType:="Char(1)")>  _
	Public Property USFL() As System.Nullable(Of Char)
		Get
			Return Me._USFL
		End Get
		Set
			If (Me._USFL.Equals(value) = false) Then
				Me._USFL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMMENTS", DbType:="VarChar(200)")>  _
	Public Property COMMENTS() As String
		Get
			Return Me._COMMENTS
		End Get
		Set
			If (String.Equals(Me._COMMENTS, value) = false) Then
				Me._COMMENTS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MODITIME", DbType:="DateTime")>  _
	Public Property MODITIME() As System.Nullable(Of Date)
		Get
			Return Me._MODITIME
		End Get
		Set
			If (Me._MODITIME.Equals(value) = false) Then
				Me._MODITIME = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ST_PPTN_R")>  _
Partial Public Class ST_PPTN_R
	
	Private _STCD As String
	
	Private _TM As Date
	
	Private _DRP As System.Nullable(Of Decimal)
	
	Private _INTV As System.Nullable(Of Decimal)
	
	Private _PDR As System.Nullable(Of Decimal)
	
	Private _DYP As System.Nullable(Of Decimal)
	
	Private _WTH As System.Nullable(Of Char)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STCD", DbType:="Char(8) NOT NULL", CanBeNull:=false)>  _
	Public Property STCD() As String
		Get
			Return Me._STCD
		End Get
		Set
			If (String.Equals(Me._STCD, value) = false) Then
				Me._STCD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TM", DbType:="DateTime NOT NULL")>  _
	Public Property TM() As Date
		Get
			Return Me._TM
		End Get
		Set
			If ((Me._TM = value)  _
						= false) Then
				Me._TM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DRP", DbType:="Decimal(5,1)")>  _
	Public Property DRP() As System.Nullable(Of Decimal)
		Get
			Return Me._DRP
		End Get
		Set
			If (Me._DRP.Equals(value) = false) Then
				Me._DRP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INTV", DbType:="Decimal(5,2)")>  _
	Public Property INTV() As System.Nullable(Of Decimal)
		Get
			Return Me._INTV
		End Get
		Set
			If (Me._INTV.Equals(value) = false) Then
				Me._INTV = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PDR", DbType:="Decimal(5,2)")>  _
	Public Property PDR() As System.Nullable(Of Decimal)
		Get
			Return Me._PDR
		End Get
		Set
			If (Me._PDR.Equals(value) = false) Then
				Me._PDR = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DYP", DbType:="Decimal(5,1)")>  _
	Public Property DYP() As System.Nullable(Of Decimal)
		Get
			Return Me._DYP
		End Get
		Set
			If (Me._DYP.Equals(value) = false) Then
				Me._DYP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WTH", DbType:="Char(1)")>  _
	Public Property WTH() As System.Nullable(Of Char)
		Get
			Return Me._WTH
		End Get
		Set
			If (Me._WTH.Equals(value) = false) Then
				Me._WTH = value
			End If
		End Set
	End Property
End Class
