'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.225
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Rw")>  _
Partial Public Class DataRwDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "可扩展性方法定义"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertST_RSVR_R(instance As ST_RSVR_R)
    End Sub
  Partial Private Sub UpdateST_RSVR_R(instance As ST_RSVR_R)
    End Sub
  Partial Private Sub DeleteST_RSVR_R(instance As ST_RSVR_R)
    End Sub
  Partial Private Sub InsertST_PPTN_R(instance As ST_PPTN_R)
    End Sub
  Partial Private Sub UpdateST_PPTN_R(instance As ST_PPTN_R)
    End Sub
  Partial Private Sub DeleteST_PPTN_R(instance As ST_PPTN_R)
    End Sub
  Partial Private Sub InsertST_STBPRP_B(instance As ST_STBPRP_B)
    End Sub
  Partial Private Sub UpdateST_STBPRP_B(instance As ST_STBPRP_B)
    End Sub
  Partial Private Sub DeleteST_STBPRP_B(instance As ST_STBPRP_B)
    End Sub
  #End Region
	
	Public Sub New()
        MyBase.New(Global.Rw.EntityData.RwEntitySettings.MySettings.Default.RwConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property ST_RSVR_R() As System.Data.Linq.Table(Of ST_RSVR_R)
		Get
			Return Me.GetTable(Of ST_RSVR_R)
		End Get
	End Property
	
	Public ReadOnly Property ST_PPTN_R() As System.Data.Linq.Table(Of ST_PPTN_R)
		Get
			Return Me.GetTable(Of ST_PPTN_R)
		End Get
	End Property
	
	Public ReadOnly Property ST_STBPRP_B() As System.Data.Linq.Table(Of ST_STBPRP_B)
		Get
			Return Me.GetTable(Of ST_STBPRP_B)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ST_RSVR_R")>  _
Partial Public Class ST_RSVR_R
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _STCD As String
	
	Private _TM As Date
	
	Private _RZ As System.Nullable(Of Decimal)
	
	Private _INQ As System.Nullable(Of Decimal)
	
	Private _W As System.Nullable(Of Decimal)
	
	Private _BLRZ As System.Nullable(Of Decimal)
	
	Private _OTQ As System.Nullable(Of Decimal)
	
	Private _RWCHRCD As System.Nullable(Of Char)
	
	Private _RWPTN As System.Nullable(Of Char)
	
	Private _INQDR As System.Nullable(Of Decimal)
	
	Private _MSQMT As System.Nullable(Of Char)
	
    #Region "可扩展性方法定义"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnSTCDChanging(value As String)
    End Sub
    Partial Private Sub OnSTCDChanged()
    End Sub
    Partial Private Sub OnTMChanging(value As Date)
    End Sub
    Partial Private Sub OnTMChanged()
    End Sub
    Partial Private Sub OnRZChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnRZChanged()
    End Sub
    Partial Private Sub OnINQChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnINQChanged()
    End Sub
    Partial Private Sub OnWChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnWChanged()
    End Sub
    Partial Private Sub OnBLRZChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnBLRZChanged()
    End Sub
    Partial Private Sub OnOTQChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnOTQChanged()
    End Sub
    Partial Private Sub OnRWCHRCDChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnRWCHRCDChanged()
    End Sub
    Partial Private Sub OnRWPTNChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnRWPTNChanged()
    End Sub
    Partial Private Sub OnINQDRChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnINQDRChanged()
    End Sub
    Partial Private Sub OnMSQMTChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnMSQMTChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STCD", DbType:="Char(8) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property STCD() As String
		Get
			Return Me._STCD
		End Get
		Set
			If (String.Equals(Me._STCD, value) = false) Then
				Me.OnSTCDChanging(value)
				Me.SendPropertyChanging
				Me._STCD = value
				Me.SendPropertyChanged("STCD")
				Me.OnSTCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TM", DbType:="DateTime NOT NULL", IsPrimaryKey:=true)>  _
	Public Property TM() As Date
		Get
			Return Me._TM
		End Get
		Set
			If ((Me._TM = value)  _
						= false) Then
				Me.OnTMChanging(value)
				Me.SendPropertyChanging
				Me._TM = value
				Me.SendPropertyChanged("TM")
				Me.OnTMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RZ", DbType:="Decimal(7,3)")>  _
	Public Property RZ() As System.Nullable(Of Decimal)
		Get
			Return Me._RZ
		End Get
		Set
			If (Me._RZ.Equals(value) = false) Then
				Me.OnRZChanging(value)
				Me.SendPropertyChanging
				Me._RZ = value
				Me.SendPropertyChanged("RZ")
				Me.OnRZChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INQ", DbType:="Decimal(9,3)")>  _
	Public Property INQ() As System.Nullable(Of Decimal)
		Get
			Return Me._INQ
		End Get
		Set
			If (Me._INQ.Equals(value) = false) Then
				Me.OnINQChanging(value)
				Me.SendPropertyChanging
				Me._INQ = value
				Me.SendPropertyChanged("INQ")
				Me.OnINQChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_W", DbType:="Decimal(9,3)")>  _
	Public Property W() As System.Nullable(Of Decimal)
		Get
			Return Me._W
		End Get
		Set
			If (Me._W.Equals(value) = false) Then
				Me.OnWChanging(value)
				Me.SendPropertyChanging
				Me._W = value
				Me.SendPropertyChanged("W")
				Me.OnWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BLRZ", DbType:="Decimal(7,3)")>  _
	Public Property BLRZ() As System.Nullable(Of Decimal)
		Get
			Return Me._BLRZ
		End Get
		Set
			If (Me._BLRZ.Equals(value) = false) Then
				Me.OnBLRZChanging(value)
				Me.SendPropertyChanging
				Me._BLRZ = value
				Me.SendPropertyChanged("BLRZ")
				Me.OnBLRZChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OTQ", DbType:="Decimal(9,3)")>  _
	Public Property OTQ() As System.Nullable(Of Decimal)
		Get
			Return Me._OTQ
		End Get
		Set
			If (Me._OTQ.Equals(value) = false) Then
				Me.OnOTQChanging(value)
				Me.SendPropertyChanging
				Me._OTQ = value
				Me.SendPropertyChanged("OTQ")
				Me.OnOTQChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RWCHRCD", DbType:="Char(1)")>  _
	Public Property RWCHRCD() As System.Nullable(Of Char)
		Get
			Return Me._RWCHRCD
		End Get
		Set
			If (Me._RWCHRCD.Equals(value) = false) Then
				Me.OnRWCHRCDChanging(value)
				Me.SendPropertyChanging
				Me._RWCHRCD = value
				Me.SendPropertyChanged("RWCHRCD")
				Me.OnRWCHRCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RWPTN", DbType:="Char(1)")>  _
	Public Property RWPTN() As System.Nullable(Of Char)
		Get
			Return Me._RWPTN
		End Get
		Set
			If (Me._RWPTN.Equals(value) = false) Then
				Me.OnRWPTNChanging(value)
				Me.SendPropertyChanging
				Me._RWPTN = value
				Me.SendPropertyChanged("RWPTN")
				Me.OnRWPTNChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INQDR", DbType:="Decimal(5,2)")>  _
	Public Property INQDR() As System.Nullable(Of Decimal)
		Get
			Return Me._INQDR
		End Get
		Set
			If (Me._INQDR.Equals(value) = false) Then
				Me.OnINQDRChanging(value)
				Me.SendPropertyChanging
				Me._INQDR = value
				Me.SendPropertyChanged("INQDR")
				Me.OnINQDRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MSQMT", DbType:="Char(1)")>  _
	Public Property MSQMT() As System.Nullable(Of Char)
		Get
			Return Me._MSQMT
		End Get
		Set
			If (Me._MSQMT.Equals(value) = false) Then
				Me.OnMSQMTChanging(value)
				Me.SendPropertyChanging
				Me._MSQMT = value
				Me.SendPropertyChanged("MSQMT")
				Me.OnMSQMTChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ST_PPTN_R")>  _
Partial Public Class ST_PPTN_R
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _STCD As String
	
	Private _TM As Date
	
	Private _DRP As System.Nullable(Of Decimal)
	
	Private _INTV As System.Nullable(Of Decimal)
	
	Private _PDR As System.Nullable(Of Decimal)
	
	Private _DYP As System.Nullable(Of Decimal)
	
	Private _WTH As System.Nullable(Of Char)
	
    #Region "可扩展性方法定义"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnSTCDChanging(value As String)
    End Sub
    Partial Private Sub OnSTCDChanged()
    End Sub
    Partial Private Sub OnTMChanging(value As Date)
    End Sub
    Partial Private Sub OnTMChanged()
    End Sub
    Partial Private Sub OnDRPChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnDRPChanged()
    End Sub
    Partial Private Sub OnINTVChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnINTVChanged()
    End Sub
    Partial Private Sub OnPDRChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPDRChanged()
    End Sub
    Partial Private Sub OnDYPChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnDYPChanged()
    End Sub
    Partial Private Sub OnWTHChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnWTHChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STCD", DbType:="Char(8) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property STCD() As String
		Get
			Return Me._STCD
		End Get
		Set
			If (String.Equals(Me._STCD, value) = false) Then
				Me.OnSTCDChanging(value)
				Me.SendPropertyChanging
				Me._STCD = value
				Me.SendPropertyChanged("STCD")
				Me.OnSTCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TM", DbType:="DateTime NOT NULL", IsPrimaryKey:=true)>  _
	Public Property TM() As Date
		Get
			Return Me._TM
		End Get
		Set
			If ((Me._TM = value)  _
						= false) Then
				Me.OnTMChanging(value)
				Me.SendPropertyChanging
				Me._TM = value
				Me.SendPropertyChanged("TM")
				Me.OnTMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DRP", DbType:="Decimal(5,1)")>  _
	Public Property DRP() As System.Nullable(Of Decimal)
		Get
			Return Me._DRP
		End Get
		Set
			If (Me._DRP.Equals(value) = false) Then
				Me.OnDRPChanging(value)
				Me.SendPropertyChanging
				Me._DRP = value
				Me.SendPropertyChanged("DRP")
				Me.OnDRPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INTV", DbType:="Decimal(5,2)")>  _
	Public Property INTV() As System.Nullable(Of Decimal)
		Get
			Return Me._INTV
		End Get
		Set
			If (Me._INTV.Equals(value) = false) Then
				Me.OnINTVChanging(value)
				Me.SendPropertyChanging
				Me._INTV = value
				Me.SendPropertyChanged("INTV")
				Me.OnINTVChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PDR", DbType:="Decimal(5,2)")>  _
	Public Property PDR() As System.Nullable(Of Decimal)
		Get
			Return Me._PDR
		End Get
		Set
			If (Me._PDR.Equals(value) = false) Then
				Me.OnPDRChanging(value)
				Me.SendPropertyChanging
				Me._PDR = value
				Me.SendPropertyChanged("PDR")
				Me.OnPDRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DYP", DbType:="Decimal(5,1)")>  _
	Public Property DYP() As System.Nullable(Of Decimal)
		Get
			Return Me._DYP
		End Get
		Set
			If (Me._DYP.Equals(value) = false) Then
				Me.OnDYPChanging(value)
				Me.SendPropertyChanging
				Me._DYP = value
				Me.SendPropertyChanged("DYP")
				Me.OnDYPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WTH", DbType:="Char(1)")>  _
	Public Property WTH() As System.Nullable(Of Char)
		Get
			Return Me._WTH
		End Get
		Set
			If (Me._WTH.Equals(value) = false) Then
				Me.OnWTHChanging(value)
				Me.SendPropertyChanging
				Me._WTH = value
				Me.SendPropertyChanged("WTH")
				Me.OnWTHChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ST_STBPRP_B")>  _
Partial Public Class ST_STBPRP_B
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _STCD As String
	
	Private _STNM As String
	
	Private _RVNM As String
	
	Private _HNNM As String
	
	Private _BSNM As String
	
	Private _LGTD As System.Nullable(Of Decimal)
	
	Private _LTTD As System.Nullable(Of Decimal)
	
	Private _STLC As String
	
	Private _ADDVCD As String
	
	Private _DTMNM As String
	
	Private _DTMEL As System.Nullable(Of Decimal)
	
	Private _DTPR As System.Nullable(Of Decimal)
	
	Private _STTP As String
	
	Private _FRGRD As System.Nullable(Of Char)
	
	Private _ESSTYM As String
	
	Private _BGFRYM As String
	
	Private _ATCUNIT As String
	
	Private _ADMAUTH As String
	
	Private _LOCALITY As String
	
	Private _STBK As System.Nullable(Of Char)
	
	Private _STAZT As System.Nullable(Of Decimal)
	
	Private _DSTRVM As System.Nullable(Of Decimal)
	
	Private _DRNA As System.Nullable(Of Decimal)
	
	Private _PHCD As String
	
	Private _USFL As System.Nullable(Of Char)
	
	Private _COMMENTS As String
	
	Private _MODITIME As System.Nullable(Of Date)
	
    #Region "可扩展性方法定义"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnSTCDChanging(value As String)
    End Sub
    Partial Private Sub OnSTCDChanged()
    End Sub
    Partial Private Sub OnSTNMChanging(value As String)
    End Sub
    Partial Private Sub OnSTNMChanged()
    End Sub
    Partial Private Sub OnRVNMChanging(value As String)
    End Sub
    Partial Private Sub OnRVNMChanged()
    End Sub
    Partial Private Sub OnHNNMChanging(value As String)
    End Sub
    Partial Private Sub OnHNNMChanged()
    End Sub
    Partial Private Sub OnBSNMChanging(value As String)
    End Sub
    Partial Private Sub OnBSNMChanged()
    End Sub
    Partial Private Sub OnLGTDChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnLGTDChanged()
    End Sub
    Partial Private Sub OnLTTDChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnLTTDChanged()
    End Sub
    Partial Private Sub OnSTLCChanging(value As String)
    End Sub
    Partial Private Sub OnSTLCChanged()
    End Sub
    Partial Private Sub OnADDVCDChanging(value As String)
    End Sub
    Partial Private Sub OnADDVCDChanged()
    End Sub
    Partial Private Sub OnDTMNMChanging(value As String)
    End Sub
    Partial Private Sub OnDTMNMChanged()
    End Sub
    Partial Private Sub OnDTMELChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnDTMELChanged()
    End Sub
    Partial Private Sub OnDTPRChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnDTPRChanged()
    End Sub
    Partial Private Sub OnSTTPChanging(value As String)
    End Sub
    Partial Private Sub OnSTTPChanged()
    End Sub
    Partial Private Sub OnFRGRDChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnFRGRDChanged()
    End Sub
    Partial Private Sub OnESSTYMChanging(value As String)
    End Sub
    Partial Private Sub OnESSTYMChanged()
    End Sub
    Partial Private Sub OnBGFRYMChanging(value As String)
    End Sub
    Partial Private Sub OnBGFRYMChanged()
    End Sub
    Partial Private Sub OnATCUNITChanging(value As String)
    End Sub
    Partial Private Sub OnATCUNITChanged()
    End Sub
    Partial Private Sub OnADMAUTHChanging(value As String)
    End Sub
    Partial Private Sub OnADMAUTHChanged()
    End Sub
    Partial Private Sub OnLOCALITYChanging(value As String)
    End Sub
    Partial Private Sub OnLOCALITYChanged()
    End Sub
    Partial Private Sub OnSTBKChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnSTBKChanged()
    End Sub
    Partial Private Sub OnSTAZTChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnSTAZTChanged()
    End Sub
    Partial Private Sub OnDSTRVMChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnDSTRVMChanged()
    End Sub
    Partial Private Sub OnDRNAChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnDRNAChanged()
    End Sub
    Partial Private Sub OnPHCDChanging(value As String)
    End Sub
    Partial Private Sub OnPHCDChanged()
    End Sub
    Partial Private Sub OnUSFLChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnUSFLChanged()
    End Sub
    Partial Private Sub OnCOMMENTSChanging(value As String)
    End Sub
    Partial Private Sub OnCOMMENTSChanged()
    End Sub
    Partial Private Sub OnMODITIMEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnMODITIMEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STCD", DbType:="Char(8) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property STCD() As String
		Get
			Return Me._STCD
		End Get
		Set
			If (String.Equals(Me._STCD, value) = false) Then
				Me.OnSTCDChanging(value)
				Me.SendPropertyChanging
				Me._STCD = value
				Me.SendPropertyChanged("STCD")
				Me.OnSTCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STNM", DbType:="Char(30)")>  _
	Public Property STNM() As String
		Get
			Return Me._STNM
		End Get
		Set
			If (String.Equals(Me._STNM, value) = false) Then
				Me.OnSTNMChanging(value)
				Me.SendPropertyChanging
				Me._STNM = value
				Me.SendPropertyChanged("STNM")
				Me.OnSTNMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RVNM", DbType:="Char(30)")>  _
	Public Property RVNM() As String
		Get
			Return Me._RVNM
		End Get
		Set
			If (String.Equals(Me._RVNM, value) = false) Then
				Me.OnRVNMChanging(value)
				Me.SendPropertyChanging
				Me._RVNM = value
				Me.SendPropertyChanged("RVNM")
				Me.OnRVNMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HNNM", DbType:="Char(30)")>  _
	Public Property HNNM() As String
		Get
			Return Me._HNNM
		End Get
		Set
			If (String.Equals(Me._HNNM, value) = false) Then
				Me.OnHNNMChanging(value)
				Me.SendPropertyChanging
				Me._HNNM = value
				Me.SendPropertyChanged("HNNM")
				Me.OnHNNMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BSNM", DbType:="Char(30)")>  _
	Public Property BSNM() As String
		Get
			Return Me._BSNM
		End Get
		Set
			If (String.Equals(Me._BSNM, value) = false) Then
				Me.OnBSNMChanging(value)
				Me.SendPropertyChanging
				Me._BSNM = value
				Me.SendPropertyChanged("BSNM")
				Me.OnBSNMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LGTD", DbType:="Decimal(10,6)")>  _
	Public Property LGTD() As System.Nullable(Of Decimal)
		Get
			Return Me._LGTD
		End Get
		Set
			If (Me._LGTD.Equals(value) = false) Then
				Me.OnLGTDChanging(value)
				Me.SendPropertyChanging
				Me._LGTD = value
				Me.SendPropertyChanged("LGTD")
				Me.OnLGTDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LTTD", DbType:="Decimal(10,6)")>  _
	Public Property LTTD() As System.Nullable(Of Decimal)
		Get
			Return Me._LTTD
		End Get
		Set
			If (Me._LTTD.Equals(value) = false) Then
				Me.OnLTTDChanging(value)
				Me.SendPropertyChanging
				Me._LTTD = value
				Me.SendPropertyChanged("LTTD")
				Me.OnLTTDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STLC", DbType:="Char(50)")>  _
	Public Property STLC() As String
		Get
			Return Me._STLC
		End Get
		Set
			If (String.Equals(Me._STLC, value) = false) Then
				Me.OnSTLCChanging(value)
				Me.SendPropertyChanging
				Me._STLC = value
				Me.SendPropertyChanged("STLC")
				Me.OnSTLCChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ADDVCD", DbType:="Char(6)")>  _
	Public Property ADDVCD() As String
		Get
			Return Me._ADDVCD
		End Get
		Set
			If (String.Equals(Me._ADDVCD, value) = false) Then
				Me.OnADDVCDChanging(value)
				Me.SendPropertyChanging
				Me._ADDVCD = value
				Me.SendPropertyChanged("ADDVCD")
				Me.OnADDVCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DTMNM", DbType:="Char(16)")>  _
	Public Property DTMNM() As String
		Get
			Return Me._DTMNM
		End Get
		Set
			If (String.Equals(Me._DTMNM, value) = false) Then
				Me.OnDTMNMChanging(value)
				Me.SendPropertyChanging
				Me._DTMNM = value
				Me.SendPropertyChanged("DTMNM")
				Me.OnDTMNMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DTMEL", DbType:="Decimal(7,3)")>  _
	Public Property DTMEL() As System.Nullable(Of Decimal)
		Get
			Return Me._DTMEL
		End Get
		Set
			If (Me._DTMEL.Equals(value) = false) Then
				Me.OnDTMELChanging(value)
				Me.SendPropertyChanging
				Me._DTMEL = value
				Me.SendPropertyChanged("DTMEL")
				Me.OnDTMELChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DTPR", DbType:="Decimal(7,3)")>  _
	Public Property DTPR() As System.Nullable(Of Decimal)
		Get
			Return Me._DTPR
		End Get
		Set
			If (Me._DTPR.Equals(value) = false) Then
				Me.OnDTPRChanging(value)
				Me.SendPropertyChanging
				Me._DTPR = value
				Me.SendPropertyChanged("DTPR")
				Me.OnDTPRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STTP", DbType:="Char(2)")>  _
	Public Property STTP() As String
		Get
			Return Me._STTP
		End Get
		Set
			If (String.Equals(Me._STTP, value) = false) Then
				Me.OnSTTPChanging(value)
				Me.SendPropertyChanging
				Me._STTP = value
				Me.SendPropertyChanged("STTP")
				Me.OnSTTPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FRGRD", DbType:="Char(1)")>  _
	Public Property FRGRD() As System.Nullable(Of Char)
		Get
			Return Me._FRGRD
		End Get
		Set
			If (Me._FRGRD.Equals(value) = false) Then
				Me.OnFRGRDChanging(value)
				Me.SendPropertyChanging
				Me._FRGRD = value
				Me.SendPropertyChanged("FRGRD")
				Me.OnFRGRDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESSTYM", DbType:="Char(6)")>  _
	Public Property ESSTYM() As String
		Get
			Return Me._ESSTYM
		End Get
		Set
			If (String.Equals(Me._ESSTYM, value) = false) Then
				Me.OnESSTYMChanging(value)
				Me.SendPropertyChanging
				Me._ESSTYM = value
				Me.SendPropertyChanged("ESSTYM")
				Me.OnESSTYMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BGFRYM", DbType:="Char(6)")>  _
	Public Property BGFRYM() As String
		Get
			Return Me._BGFRYM
		End Get
		Set
			If (String.Equals(Me._BGFRYM, value) = false) Then
				Me.OnBGFRYMChanging(value)
				Me.SendPropertyChanging
				Me._BGFRYM = value
				Me.SendPropertyChanged("BGFRYM")
				Me.OnBGFRYMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ATCUNIT", DbType:="Char(20)")>  _
	Public Property ATCUNIT() As String
		Get
			Return Me._ATCUNIT
		End Get
		Set
			If (String.Equals(Me._ATCUNIT, value) = false) Then
				Me.OnATCUNITChanging(value)
				Me.SendPropertyChanging
				Me._ATCUNIT = value
				Me.SendPropertyChanged("ATCUNIT")
				Me.OnATCUNITChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ADMAUTH", DbType:="Char(20)")>  _
	Public Property ADMAUTH() As String
		Get
			Return Me._ADMAUTH
		End Get
		Set
			If (String.Equals(Me._ADMAUTH, value) = false) Then
				Me.OnADMAUTHChanging(value)
				Me.SendPropertyChanging
				Me._ADMAUTH = value
				Me.SendPropertyChanged("ADMAUTH")
				Me.OnADMAUTHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LOCALITY", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property LOCALITY() As String
		Get
			Return Me._LOCALITY
		End Get
		Set
			If (String.Equals(Me._LOCALITY, value) = false) Then
				Me.OnLOCALITYChanging(value)
				Me.SendPropertyChanging
				Me._LOCALITY = value
				Me.SendPropertyChanged("LOCALITY")
				Me.OnLOCALITYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STBK", DbType:="Char(1)")>  _
	Public Property STBK() As System.Nullable(Of Char)
		Get
			Return Me._STBK
		End Get
		Set
			If (Me._STBK.Equals(value) = false) Then
				Me.OnSTBKChanging(value)
				Me.SendPropertyChanging
				Me._STBK = value
				Me.SendPropertyChanged("STBK")
				Me.OnSTBKChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STAZT", DbType:="Decimal(3,0)")>  _
	Public Property STAZT() As System.Nullable(Of Decimal)
		Get
			Return Me._STAZT
		End Get
		Set
			If (Me._STAZT.Equals(value) = false) Then
				Me.OnSTAZTChanging(value)
				Me.SendPropertyChanging
				Me._STAZT = value
				Me.SendPropertyChanged("STAZT")
				Me.OnSTAZTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DSTRVM", DbType:="Decimal(6,1)")>  _
	Public Property DSTRVM() As System.Nullable(Of Decimal)
		Get
			Return Me._DSTRVM
		End Get
		Set
			If (Me._DSTRVM.Equals(value) = false) Then
				Me.OnDSTRVMChanging(value)
				Me.SendPropertyChanging
				Me._DSTRVM = value
				Me.SendPropertyChanged("DSTRVM")
				Me.OnDSTRVMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DRNA", DbType:="Decimal(7,0)")>  _
	Public Property DRNA() As System.Nullable(Of Decimal)
		Get
			Return Me._DRNA
		End Get
		Set
			If (Me._DRNA.Equals(value) = false) Then
				Me.OnDRNAChanging(value)
				Me.SendPropertyChanging
				Me._DRNA = value
				Me.SendPropertyChanged("DRNA")
				Me.OnDRNAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PHCD", DbType:="Char(6)")>  _
	Public Property PHCD() As String
		Get
			Return Me._PHCD
		End Get
		Set
			If (String.Equals(Me._PHCD, value) = false) Then
				Me.OnPHCDChanging(value)
				Me.SendPropertyChanging
				Me._PHCD = value
				Me.SendPropertyChanged("PHCD")
				Me.OnPHCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USFL", DbType:="Char(1)")>  _
	Public Property USFL() As System.Nullable(Of Char)
		Get
			Return Me._USFL
		End Get
		Set
			If (Me._USFL.Equals(value) = false) Then
				Me.OnUSFLChanging(value)
				Me.SendPropertyChanging
				Me._USFL = value
				Me.SendPropertyChanged("USFL")
				Me.OnUSFLChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMMENTS", DbType:="VarChar(200)")>  _
	Public Property COMMENTS() As String
		Get
			Return Me._COMMENTS
		End Get
		Set
			If (String.Equals(Me._COMMENTS, value) = false) Then
				Me.OnCOMMENTSChanging(value)
				Me.SendPropertyChanging
				Me._COMMENTS = value
				Me.SendPropertyChanged("COMMENTS")
				Me.OnCOMMENTSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MODITIME", DbType:="DateTime")>  _
	Public Property MODITIME() As System.Nullable(Of Date)
		Get
			Return Me._MODITIME
		End Get
		Set
			If (Me._MODITIME.Equals(value) = false) Then
				Me.OnMODITIMEChanging(value)
				Me.SendPropertyChanging
				Me._MODITIME = value
				Me.SendPropertyChanged("MODITIME")
				Me.OnMODITIMEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
