'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.34003
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>  _
    Partial Public NotInheritable Class Rw
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As Rw = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Rw()),Rw)
        
        Public Shared ReadOnly Property [Default]() As Rw
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("安徽省岳西县")>  _
        Public ReadOnly Property MapAddrName() As String
            Get
                Return CType(Me("MapAddrName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("安徽岳西县雨水情监测图")>  _
        Public ReadOnly Property MapTitle() As String
            Get
                Return CType(Me("MapTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\v11.0;AttachDbFilename=D:\Data\Rw\easy\RwData.mdf;Integrate" & _
            "d Security=True;Connect Timeout=30")> _
        Public Property DbConnStr() As String
            Get
                Return CType(Me("DbConnStr"), String)
            End Get
            Set(value As String)
                Me("DbConnStr") = value
            End Set
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("6000")> _
        Public ReadOnly Property DataFlush() As Integer
            Get
                Return CType(Me("DataFlush"), Integer)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\MrLin\RainAndWater\Rw\Rw.DAL")> _
        Public ReadOnly Property RepPath() As String
            Get
                Return CType(Me("RepPath"), String)
            End Get
        End Property
    End Class
End Namespace
