'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>  _
    Partial Public NotInheritable Class Rw
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As Rw = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Rw()),Rw)
        
        Public Shared ReadOnly Property [Default]() As Rw
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("安徽省岳西县")>  _
        Public ReadOnly Property MapAddrName() As String
            Get
                Return CType(Me("MapAddrName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("安徽岳西县雨水情监测图")>  _
        Public ReadOnly Property MapTitle() As String
            Get
                Return CType(Me("MapTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60000")>  _
        Public ReadOnly Property DataFlush() As Integer
            Get
                Return CType(Me("DataFlush"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=114.213.236.232;Initial Catalog=Rw;User ID=eliachen;Password=12345")>  _
        Public ReadOnly Property DbConnStr() As String
            Get
                Return CType(Me("DbConnStr"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property RepPath() As String
            Get
                Return CType(Me("RepPath"),String)
            End Get
        End Property
    End Class
End Namespace
