'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.34003
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReferenceWater
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReferenceWater.WebService_AnHuiSoap")>  _
    Public Interface WebService_AnHuiSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getYqXx", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getYqXx(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getSqXx", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getSqXx(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String, ByVal sttp As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getYlZzt", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getYlZzt(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String, ByVal sd As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getSwGcx", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getSwGcx(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String, ByVal sttp As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getSwGcx_Tz", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getSwGcx_Tz(ByVal stcd As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getLlGcx", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getLlGcx(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String, ByVal sttp As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getSw_BjXx", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getSw_BjXx() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getWaterInfo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getWaterInfo() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getRainInfo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getRainInfo(ByVal startTime As String, ByVal endTime As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getZxYl", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getZxYl() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getfeature", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getfeature(ByVal stcd As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AvgAreaRain", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AvgAreaRain(ByVal startTime As String, ByVal endTime As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_YL_RYLTJ", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_YL_RYLTJ(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal Ri_Yl As Double) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_YL_RYLTJ_TS", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_YL_RYLTJ_TS(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal Ri_Yl As Double) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_YL_Ri", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_YL_Ri(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_YL_Dls", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_YL_Dls(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_YL_Cls", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_YL_Cls(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal ylts As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_YL_DsPj", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_YL_DsPj(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_YL_ZdTj", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_YL_ZdTj(ByVal startTime As String, ByVal endTime As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_SW_SS", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_SW_SS(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_SW_TZZ", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_SW_TZZ() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_SW_ZD", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_SW_ZD(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_SW_ZD_OLD", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_SW_ZD_OLD(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_SW_ChaoJing", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_SW_ChaoJing(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal ChaoJingLx As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_SW_ChaoJing_OLD", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_SW_ChaoJing_OLD(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal ChaoJingLx As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_CzZt", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_CzZt(ByVal endTime As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_CzZt_OLD", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_CzZt_OLD(ByVal endTime As String) As System.Data.DataTable
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService_AnHuiSoapChannel
        Inherits ServiceReferenceWater.WebService_AnHuiSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService_AnHuiSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReferenceWater.WebService_AnHuiSoap)
        Implements ServiceReferenceWater.WebService_AnHuiSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements ServiceReferenceWater.WebService_AnHuiSoap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        Public Function getYqXx(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getYqXx
            Return MyBase.Channel.getYqXx(stcd, startTime, endTime)
        End Function
        
        Public Function getSqXx(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String, ByVal sttp As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getSqXx
            Return MyBase.Channel.getSqXx(stcd, startTime, endTime, sttp)
        End Function
        
        Public Function getYlZzt(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String, ByVal sd As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getYlZzt
            Return MyBase.Channel.getYlZzt(stcd, startTime, endTime, sd)
        End Function
        
        Public Function getSwGcx(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String, ByVal sttp As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getSwGcx
            Return MyBase.Channel.getSwGcx(stcd, startTime, endTime, sttp)
        End Function
        
        Public Function getSwGcx_Tz(ByVal stcd As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getSwGcx_Tz
            Return MyBase.Channel.getSwGcx_Tz(stcd)
        End Function
        
        Public Function getLlGcx(ByVal stcd As String, ByVal startTime As String, ByVal endTime As String, ByVal sttp As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getLlGcx
            Return MyBase.Channel.getLlGcx(stcd, startTime, endTime, sttp)
        End Function
        
        Public Function getSw_BjXx() As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getSw_BjXx
            Return MyBase.Channel.getSw_BjXx
        End Function
        
        Public Function getWaterInfo() As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getWaterInfo
            Return MyBase.Channel.getWaterInfo
        End Function
        
        Public Function getRainInfo(ByVal startTime As String, ByVal endTime As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getRainInfo
            Return MyBase.Channel.getRainInfo(startTime, endTime)
        End Function
        
        Public Function getZxYl() As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getZxYl
            Return MyBase.Channel.getZxYl
        End Function
        
        Public Function getfeature(ByVal stcd As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.getfeature
            Return MyBase.Channel.getfeature(stcd)
        End Function
        
        Public Function AvgAreaRain(ByVal startTime As String, ByVal endTime As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.AvgAreaRain
            Return MyBase.Channel.AvgAreaRain(startTime, endTime)
        End Function
        
        Public Function get_YL_RYLTJ(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal Ri_Yl As Double) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_YL_RYLTJ
            Return MyBase.Channel.get_YL_RYLTJ(startTime, endTime, QuYuLx, QuYuMing, Ri_Yl)
        End Function
        
        Public Function get_YL_RYLTJ_TS(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal Ri_Yl As Double) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_YL_RYLTJ_TS
            Return MyBase.Channel.get_YL_RYLTJ_TS(startTime, endTime, QuYuLx, QuYuMing, Ri_Yl)
        End Function
        
        Public Function get_YL_Ri(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_YL_Ri
            Return MyBase.Channel.get_YL_Ri(startTime, endTime, QuYuLx, QuYuMing)
        End Function
        
        Public Function get_YL_Dls(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_YL_Dls
            Return MyBase.Channel.get_YL_Dls(startTime, endTime, QuYuLx, QuYuMing)
        End Function
        
        Public Function get_YL_Cls(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal ylts As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_YL_Cls
            Return MyBase.Channel.get_YL_Cls(startTime, endTime, QuYuLx, QuYuMing, ylts)
        End Function
        
        Public Function get_YL_DsPj(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_YL_DsPj
            Return MyBase.Channel.get_YL_DsPj(startTime, endTime, QuYuLx)
        End Function
        
        Public Function get_YL_ZdTj(ByVal startTime As String, ByVal endTime As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_YL_ZdTj
            Return MyBase.Channel.get_YL_ZdTj(startTime, endTime)
        End Function
        
        Public Function get_SW_SS(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_SW_SS
            Return MyBase.Channel.get_SW_SS(startTime, endTime, QuYuLx, QuYuMing)
        End Function
        
        Public Function get_SW_TZZ() As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_SW_TZZ
            Return MyBase.Channel.get_SW_TZZ
        End Function
        
        Public Function get_SW_ZD(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_SW_ZD
            Return MyBase.Channel.get_SW_ZD(startTime, endTime, QuYuLx, QuYuMing)
        End Function
        
        Public Function get_SW_ZD_OLD(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_SW_ZD_OLD
            Return MyBase.Channel.get_SW_ZD_OLD(startTime, endTime, QuYuLx, QuYuMing)
        End Function
        
        Public Function get_SW_ChaoJing(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal ChaoJingLx As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_SW_ChaoJing
            Return MyBase.Channel.get_SW_ChaoJing(startTime, endTime, QuYuLx, QuYuMing, ChaoJingLx)
        End Function
        
        Public Function get_SW_ChaoJing_OLD(ByVal startTime As String, ByVal endTime As String, ByVal QuYuLx As String, ByVal QuYuMing As String, ByVal ChaoJingLx As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_SW_ChaoJing_OLD
            Return MyBase.Channel.get_SW_ChaoJing_OLD(startTime, endTime, QuYuLx, QuYuMing, ChaoJingLx)
        End Function
        
        Public Function get_CzZt(ByVal endTime As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_CzZt
            Return MyBase.Channel.get_CzZt(endTime)
        End Function
        
        Public Function get_CzZt_OLD(ByVal endTime As String) As System.Data.DataTable Implements ServiceReferenceWater.WebService_AnHuiSoap.get_CzZt_OLD
            Return MyBase.Channel.get_CzZt_OLD(endTime)
        End Function
    End Class
End Namespace
